# -*- coding: utf-8 -*-
"""Agenticai7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XOc0CbsXBOfYD9zw5-pt10FVIxXCkdkD
"""

!pip install langchain-groq -q
from langchain_groq import ChatGroq

llm = ChatGroq(api_key="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",

               model="llama-3.1-8b-instant", temperature=0)
import sqlite3

conn = sqlite3.connect('memory.db')
conn.execute('CREATE TABLE IF NOT EXISTS facts (key TEXT, value TEXT)')
conn.commit()

print('Database ready: memory.db')
def remember(key, value):
    conn.execute('INSERT INTO facts VALUES (?, ?)', (key, value))
    conn.commit()

remember('name', 'Riya')
remember('favourite_subject', 'Mathematics')
print('Saved!')
def recall_all():
    rows = conn.execute('SELECT key, value FROM facts').fetchall()
    return '; '.join(f'{k} = {v}' for k, v in rows)

memory = recall_all()
print('Recalled memory:', memory)
reply = llm.invoke(f'Known facts: {memory}. '

                   'Greet the user by name and mention their favourite subject.')

print(reply.content)