# -*- coding: utf-8 -*-
"""agenticai 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ztdUMOtxFQ5LxHWObvtvj_qQaCS0CO9
"""

import os
!pip install autogen -q
import autogen

# Set your Groq API key as an environment variable
os.environ['GROQ_API_KEY'] = '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'

config_list = [{
    'model': 'llama-3.1-8b-instant',
    'api_key': os.environ.get('GROQ_API_KEY'), # Now correctly retrieves the API key
    'base_url': 'https://api.groq.com/openai/v1'
}]

llm_config = {
    'config_list': config_list,
    'temperature': 0.4
}

writer = autogen.AssistantAgent(
    name='Writer',
    system_message='You write short, clear blog posts. When given feedback, rewrite to improve it.',
    llm_config=llm_config
)

critic = autogen.AssistantAgent(
    name='Critic',
    system_message='You review blog posts and give 2-3 specific improvements. If it is good, reply APPROVED.',
    llm_config=llm_config
)

critic.initiate_chat(
    recipient=writer,
    message='Write a 150-word blog post about the benefits of reading.',
    max_turns=4
)